M48
; DRILL file {KiCad 7.0.1} date Mon Apr 10 20:01:36 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-10T20:01:36-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X2.4Y-6.14
X2.48Y-1.36
X5.28Y-4.12
X7.2835Y-6.1417
X7.385Y-3.825
X8.0Y-1.35
X8.01Y-4.445
X8.0709Y-4.7638
T0
M30
