M48
; DRILL file {KiCad 7.0.5} date Mon Aug 28 12:49:35 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-28T12:49:35-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X2.4Y-6.14
X2.48Y-1.36
X5.28Y-4.12
X7.2835Y-6.1417
X7.385Y-3.825
X8.01Y-4.445
X8.02Y-1.34
X8.055Y-4.76
T0
M30
